---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Openshift
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: cli
    tekton.dev/displayName: "openshift client"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task runs commands against the cluster where the task run is
    being executed.
    OpenShift is a Kubernetes distribution from Red Hat which provides oc,
    the OpenShift CLI that complements kubectl for simplifying deployment
    and configuration applications on OpenShift.
  params:
    - name: SCRIPT
      description: The OpenShift CLI arguments to run
      type: string
      default: "oc $@"
    - name: ARGS
      description: The OpenShift CLI arguments to run
      type: array
      default:
        - "help"
    - name: VERSION
      description: The OpenShift Version to use
      type: string
      default: "4.10"
  resources:
    inputs:
      - name: source
        type: git
        optional: true
  results:
    - name: oc-output
      description: The output of the oc command
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:$(params.VERSION)
      script: "$(params.SCRIPT)"
      args:
        - "$(params.ARGS)"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: base-cp4d
spec:
  params:
    - name: namespace
      type: string
      description: Namespace for Cloud Pak Deployer deployment
      default: "cloud-pak-deployer"
    - name: ocp-client-version
      type: string
      description: Openshift client version
      default: "4.10"
  tasks:
    - name: configure-cloud-paks-services
      taskRef:
        name: openshift-client
      params:
        - name: ARGS
          value: [$(params.namespace)]
        - name: VERSION
          value: $(params.ocp-client-version)
        - name: SCRIPT
          value: |
            oc apply -f - <<EOF
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: cloud-pak-deployer-config
              namespace: $1
            data:
              cpd-config.yaml: |
                global_config:
                  environment_name: demo
                  cloud_platform: existing-ocp
                  confirm_destroy: False

                openshift:
                - name: cpd-demo
                  ocp_version: '$(params.ocp-client-version)'
                  cluster_name: cpd-demo
                  domain_name: example.com
                  openshift_storage:
                  - storage_name: auto-storage
                    storage_type: ocs

                cp4d:
                - project: cpd
                  openshift_cluster_name: cpd-demo
                  cp4d_version: 4.6.4
                  sequential_install: True
                  accept_licenses: True
                  cartridges:
                  - name: cp-foundation
                    license_service:
                      state: disabled
                      threads_per_core: 2
                  - name: lite

                  - name: analyticsengine 
                    size: small 
                    state: removed

                  - name: bigsql
                    state: removed

                  - name: ca
                    size: small
                    instances:
                    - name: ca-instance
                      metastore_ref: ca-metastore
                    state: removed

                  - name: cde
                    state: removed

                  - name: datagate
                    state: removed

                  - name: datastage-ent-plus
                    state: removed

                  - name: db2
                    size: small
                    instances:
                    - name: ca-metastore
                      metadata_size_gb: 20
                      data_size_gb: 20
                      backup_size_gb: 20  
                      transactionlog_size_gb: 20
                    state: removed

                  - name: db2wh
                    state: removed

                  - name: dmc
                    state: removed

                  - name: dods
                    size: small
                    state: removed

                  - name: dp
                    size: small
                    state: removed

                  - name: dv
                    size: small 
                    instances:
                    - name: data-virtualization
                    state: removed

                  - name: factsheet
                    size: small
                    state: removed

                  - name: hadoop
                    size: small
                    state: removed

                  - name: mdm
                    size: small
                    wkc_enabled: true
                    state: removed

                  - name: openpages
                    state: removed
                    instances:
                    - name: openpages-instance
                      size: xsmall

                  - name: planning-analytics
                    state: removed

                  - name: rstudio
                    size: small
                    state: removed

                  - name: spss
                    state: removed

                  - name: voice-gateway
                    replicas: 1
                    state: removed

                  - name: watson-assistant
                    size: small
                    state: removed

                  - name: watson-discovery
                    state: removed

                  - name: watson-ks
                    size: small
                    state: removed

                  - name: watson-openscale
                    size: small
                    state: removed

                  - name: watson-speech
                    stt_size: xsmall
                    tts_size: xsmall
                    state: removed

                  - name: wkc
                    size: small
                    state: removed
                    installation_options:
                      install_wkc_core_only: True
                      enableKnowledgeGraph: False
                      enableDataQuality: False
                      enableFactSheet: False
                      enableMANTA: False

                  - name: wml
                    size: small
                    state: removed

                  - name: wml-accelerator
                    replicas: 1
                    size: small
                    state: removed

                  - name: wsl
                    state: removed

                  - name: ws-pipelines
                    state: removed
            EOF
    - name: delete-previous-job
      taskRef:
        name: openshift-client
      runAfter:
        - configure-cloud-paks-services
      params:
        - name: ARGS
          value: [$(params.namespace)]
        - name: VERSION
          value: $(params.ocp-client-version)
        - name: SCRIPT
          value: |
            oc delete job cloud-pak-deployer -n $1 --ignore-not-found
    - name: run-the-deployer
      taskRef:
        name: openshift-client
      runAfter:
        - delete-previous-job
      params:
        - name: ARGS
          value: [$(params.namespace)]
        - name: VERSION
          value: $(params.ocp-client-version)
        - name: SCRIPT
          value: |
            oc apply -f - <<EOF
            apiVersion: batch/v1
            kind: Job
            metadata:
              labels:
                app: cloud-pak-deployer
              name: cloud-pak-deployer
              namespace: $1
            spec:
              parallelism: 1
              completions: 1
              backoffLimit: 0
              template:
                metadata:
                  name: cloud-pak-deployer
                  labels:
                    app: cloud-pak-deployer
                spec:
                  containers:
                  - name: cloud-pak-deployer
                    image: quay.io/cloud-pak-deployer/cloud-pak-deployer:latest
                    imagePullPolicy: Always
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    env:
                    - name: CONFIG_DIR
                      value: /Data/cpd-config
                    - name: STATUS_DIR
                      value: /Data/cpd-status
                    - name: CP_ENTITLEMENT_KEY
                      valueFrom:
                        secretKeyRef:
                          key: cp-entitlement-key
                          name: cloud-pak-entitlement-key
                    volumeMounts:
                    - name: config-volume
                      mountPath: /Data/cpd-config/config
                    - name: status-volume
                      mountPath: /Data/cpd-status
                    command: ["/bin/sh","-xc"]
                    args: 
                      - /cloud-pak-deployer/cp-deploy.sh env apply -v
                  restartPolicy: Never
                  securityContext:
                    runAsUser: 0
                  serviceAccountName: cloud-pak-deployer-sa
                  volumes:
                  - name: config-volume
                    configMap:
                      name: cloud-pak-deployer-config
                  - name: status-volume
                    persistentVolumeClaim:
                      claimName: cloud-pak-deployer-status
            EOF
