apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cloud-pak-deployer-4.8.1-data-governance-run-
spec:
  timeouts:
    pipeline: 6h0m0s
  pipelineRef:
    name: cloud-pak-deployer-4.8-data-governance
  params:
    - name: namespace
      value: "cloud-pak-deployer"
    - name: storage-class
      value: "ocs-storagecluster-cephfs"
    - name: ocp-client-version
      value: "4.14"
    - name: cp4d-version
      value: "4.8.1"
    - name: ibm-entitlement-key
      value: "false"
    - name: analyticsengine-state
      value: "installed"
    - name: dashboard-state
      value: "installed"
    - name: datastage-ent-plus-state
      value: "installed"
    - name: db2-state
      value: "installed"
    - name: dmc-state
      value: "installed"
    - name: dp-state
      value: "installed"
    - name: dv-state
      value: "installed"
    - name: mantaflow-state
      value: "installed"
    - name: wkc-state
      value: "installed"
    - name: wkc-options-core-only
      value: "True"
    - name: wkc-options-knowledge-graph
      value: "True"
    - name: wkc-options-enable-data-quality
      value: "True"
