apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cloud-pak-deployer-run
spec:
  timeout: 6h0m0s
  pipelineRef:
    name: cloud-pak-deployer
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: namespace
      value: "cloud-pak-deployer"
    - name: storage-class
      value: "ocs-storagecluster-cephfs"
    - name: ocp-client-version
      value: "4.10"
    - name: cp4d-version
      value: "4.6.4"
    - name: ibm-entitlement-key
      value: "false"
