apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cloud-pak-deployer-4.8.3-ds-mlops-run-
spec:
  timeouts:
    pipeline: 6h0m0s
  pipelineRef:
    name: cloud-pak-deployer-4.8.3-ds-mlops
  params:
    - name: namespace
      value: "cloud-pak-deployer"
    - name: storage-class
      value: "ocs-storagecluster-cephfs"
    - name: ocp-client-version
      value: "4.14"
    - name: cp4d-version
      value: "4.8.3"
    - name: ibm-entitlement-key
      value: "false"
    - name: analyticsengine-state
      value: "installed"
    - name: spss-state
      value: "installed"
    - name: wml-state
      value: "installed"
    - name: ws-state
      value: "installed"
    - name: ws-runtimes-state
      value: "installed"
