apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cloud-pak-deployer-4.8.3-ai-governance-run-
spec:
  timeouts:
    pipeline: 8h0m0s
  pipelineRef:
    name: cloud-pak-deployer-4.8.3-ai-governance
  params:
    - name: namespace
      value: "cloud-pak-deployer"
    - name: storage-class
      value: "ocs-storagecluster-cephfs"
    - name: ocp-client-version
      value: "4.14"
    - name: cp4d-version
      value: "4.8.3"
    - name: ibm-entitlement-key
      value: "false"
    - name: analyticsengine-state
      value: "installed"
    - name: db2-state
      value: "installed"
    - name: dmc-state
      value: "installed"
    - name: factsheet-state
      value: "installed"
    - name: openpages-state
      value: "installed"
    - name: spss-state
      value: "installed"
    - name: watson-openscale-state
      value: "installed"
    - name: wkc-state
      value: "installed"
    - name: wkc-options-core-only
      value: "True"
    - name: wkc-options-knowledge-graph
      value: "False"
    - name: wkc-options-enable-data-quality
      value: "False"
    - name: wml-state
      value: "installed"
    - name: ws-state
      value: "installed"
    - name: ws-runtimes-state
      value: "installed"
