apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cloud-pak-deployer-run-
spec:
  timeout: 6h0m0s
  pipelineRef:
    name: cloud-pak-deployer
  params:
    - name: namespace
      value: "cloud-pak-deployer"
    - name: storage-class
      value: "ocs-storagecluster-cephfs"
    - name: ocp-client-version
      value: "4.12"
    - name: cp4d-version
      value: "4.7.0"
    - name: ibm-entitlement-key
      value: "false"
    - name: ca-state
      value: "installed"
    - name: ws-state
      value: "installed"
    - name: db2-state
      value: "installed"
